In [6]:
import sys
sys.path.append('/Users/tunadorable/local-repos/next-concept-predictor/venv/lib/python3.11/site-packages')

import torch
import torch.nn as nn

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [8]:
# Example for a single linear layer
class SingleLayerNet(nn.Module):
    def __init__(self, n, d, v):
        super(SingleLayerNet, self).__init__()
        self.linear = nn.Linear(d, v, bias=False)  # Single linear layer

    def forward(self, x):
        return self.linear(x)

    def get_weights_for_row(self, i):
        # Return the i-th row of the weight matrix
        return self.linear.weight[i, :]

In [9]:
# Example for two linear layers
class TwoLayerNet(nn.Module):
    def __init__(self, n, d, m, v):
        super(TwoLayerNet, self).__init__()
        self.linear1 = nn.Linear(d, m, bias=False)  # First linear layer
        self.linear2 = nn.Linear(m, v, bias=False)  # Second linear layer

    def forward(self, x):
        y = self.linear1(x)
        return self.linear2(y)

    def get_weights_for_row(self, i):
        # Return the i-th row of the second weight matrix
        return self.linear2.weight[i, :]

In [10]:
# Initialize models
n, d, m, v = 10, 5, 8, 4  # Dimensions
single_layer_net = SingleLayerNet(n, d, v)
two_layer_net = TwoLayerNet(n, d, m, v)

In [11]:
# Example row index
i = 2  # Assuming indexing starts from 0

# Extract weights for the specific row from both models
weights_single_layer = single_layer_net.get_weights_for_row(i)
weights_two_layer = two_layer_net.get_weights_for_row(i)

weights_single_layer, weights_two_layer

(tensor([-0.2542, -0.3025, -0.0300, -0.1169, -0.3656], grad_fn=<SliceBackward0>),
 tensor([ 0.0367,  0.2663,  0.1705, -0.3114,  0.0559, -0.0570, -0.2811,  0.3400],
        grad_fn=<SliceBackward0>))